[package]
name = "integration_test"
version = "0.1.0"
authors = ["Steven Roose <steven@stevenroose.org>"]
edition = "2018"

[dependencies]
ord-bitcoincore-rpc = { path = "../client" }
bitcoin = { path = "../../rust-qtum/bitcoin", version = "0.30.0-qtum", features = ["serde", "rand"]}
lazy_static = "1.4.0"
log = "0.4"
